@EcoTrace.Identity_HostAddress = http://localhost:5002

### Obtener todos los tenants
GET {{EcoTrace.Identity_HostAddress}}/api/tenants
Accept: application/json

### Crear un tenant Generador
POST {{EcoTrace.Identity_HostAddress}}/api/tenants
Content-Type: application/json

{
  "name": "EcoIndustrias SAS",
  "taxId": "901234567-1",
  "type": 1
}

### Crear un tenant Transportista
POST {{EcoTrace.Identity_HostAddress}}/api/tenants
Content-Type: application/json

{
  "name": "Transportes Verdes Colombia",
  "taxId": "900876543-2",
  "type": 2
}

### Obtener todos los roles
GET {{EcoTrace.Identity_HostAddress}}/api/roles
Accept: application/json

### Crear un rol
POST {{EcoTrace.Identity_HostAddress}}/api/roles
Content-Type: application/json

{
  "name": "Driver",
  "description": "Conductor de flota de transporte"
}

### Obtener usuarios
GET {{EcoTrace.Identity_HostAddress}}/api/users
Accept: application/json
