// <auto-generated />
using System;
using EcoTrace.CargoTracking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTrace.CargoTracking.Infrastructure.Migrations
{
    [DbContext(typeof(CargoTrackingDbContext))]
    partial class CargoTrackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.AsignacionCarga", b =>
                {
                    b.Property<Guid>("AsignacionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AsignadaEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CargaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConductorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("TEXT");

                    b.HasKey("AsignacionId");

                    b.HasIndex("CargaId")
                        .IsUnique();

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Asignaciones", (string)null);
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.Carga", b =>
                {
                    b.Property<Guid>("CargaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GeneradorTenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PesoKg")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransportistaTenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("CargaId");

                    b.HasIndex("Estado");

                    b.HasIndex("GeneradorTenantId");

                    b.HasIndex("TransportistaTenantId");

                    b.ToTable("Cargas", (string)null);
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.Seguimiento", b =>
                {
                    b.Property<Guid>("SeguimientoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CargaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistradoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("SeguimientoId");

                    b.HasIndex("CargaId");

                    b.ToTable("Seguimientos", (string)null);
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.AsignacionCarga", b =>
                {
                    b.HasOne("EcoTrace.CargoTracking.Domain.Carga", null)
                        .WithOne("Asignacion")
                        .HasForeignKey("EcoTrace.CargoTracking.Domain.AsignacionCarga", "CargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.Seguimiento", b =>
                {
                    b.HasOne("EcoTrace.CargoTracking.Domain.Carga", null)
                        .WithMany("Seguimientos")
                        .HasForeignKey("CargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.Carga", b =>
                {
                    b.Navigation("Asignacion");

                    b.Navigation("Seguimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
