// <auto-generated />
using System;
using EcoTrace.Identity.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTrace.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260920193014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("EcoTrace.Identity.Domain.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Nombre = "Conductor"
                        },
                        new
                        {
                            RoleId = 2,
                            Nombre = "Supervisor"
                        },
                        new
                        {
                            RoleId = 3,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            RoleId = 4,
                            Nombre = "Auditor"
                        });
                });

            modelBuilder.Entity("EcoTrace.Identity.Domain.RoleClaim", b =>
                {
                    b.Property<int>("RoleClaimId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleClaimId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            RoleClaimId = 1,
                            RoleId = 1,
                            Tipo = "permiso",
                            Valor = "cargas.confirmar_entrega"
                        },
                        new
                        {
                            RoleClaimId = 2,
                            RoleId = 1,
                            Tipo = "permiso",
                            Valor = "seguimiento.registrar"
                        },
                        new
                        {
                            RoleClaimId = 3,
                            RoleId = 2,
                            Tipo = "permiso",
                            Valor = "flota.gestionar"
                        },
                        new
                        {
                            RoleClaimId = 4,
                            RoleId = 2,
                            Tipo = "permiso",
                            Valor = "cargas.asignar"
                        },
                        new
                        {
                            RoleClaimId = 5,
                            RoleId = 3,
                            Tipo = "permiso",
                            Valor = "organizaciones.gestionar"
                        },
                        new
                        {
                            RoleClaimId = 6,
                            RoleId = 3,
                            Tipo = "permiso",
                            Valor = "usuarios.gestionar"
                        },
                        new
                        {
                            RoleClaimId = 7,
                            RoleId = 4,
                            Tipo = "permiso",
                            Valor = "auditoria.leer"
                        });
                });

            modelBuilder.Entity("EcoTrace.Identity.Domain.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("EcoTrace.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EcoTrace.Identity.Domain.RoleClaim", b =>
                {
                    b.HasOne("EcoTrace.Identity.Domain.Role", null)
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoTrace.Identity.Domain.User", b =>
                {
                    b.HasOne("EcoTrace.Identity.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoTrace.Identity.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EcoTrace.Identity.Domain.Role", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
