// <auto-generated />
using System;
using EcoTrace.Billing.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTrace.Billing.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("EcoTrace.Billing.Domain.AuditoriaFinanciera", b =>
                {
                    b.Property<Guid>("AuditoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoResultante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditoriaId");

                    b.HasIndex("PagoId");

                    b.ToTable("AuditoriaFinanciera", (string)null);
                });

            modelBuilder.Entity("EcoTrace.Billing.Domain.Factura", b =>
                {
                    b.Property<Guid>("FacturaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CargaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmitidaEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GeneradorTenantId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransportistaTenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("FacturaId");

                    b.HasIndex("CargaId")
                        .IsUnique();

                    b.HasIndex("GeneradorTenantId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("TransportistaTenantId");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("EcoTrace.Billing.Domain.Pago", b =>
                {
                    b.Property<Guid>("PagoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CargaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoEscrow")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GeneradorTenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransportistaTenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("PagoId");

                    b.HasIndex("CargaId")
                        .IsUnique();

                    b.HasIndex("GeneradorTenantId");

                    b.HasIndex("TransportistaTenantId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("EcoTrace.Billing.Domain.AuditoriaFinanciera", b =>
                {
                    b.HasOne("EcoTrace.Billing.Domain.Pago", null)
                        .WithMany("Auditoria")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoTrace.Billing.Domain.Pago", b =>
                {
                    b.Navigation("Auditoria");
                });
#pragma warning restore 612, 618
        }
    }
}
