// <auto-generated />
using System;
using EcoTrace.CargoTracking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoTrace.CargoTracking.Migrations
{
    [DbContext(typeof(CargoTrackingDbContext))]
    [Migration("20260917042831_InicialSegunADR")]
    partial class InicialSegunADR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.AsignacionCarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConductorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CargaId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.Carga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GeneradorTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransportistaTenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Cargas");
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.Seguimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CargaId");

                    b.ToTable("Seguimientos");
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.AsignacionCarga", b =>
                {
                    b.HasOne("EcoTrace.CargoTracking.Domain.Carga", "Carga")
                        .WithMany("Asignaciones")
                        .HasForeignKey("CargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carga");
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.Seguimiento", b =>
                {
                    b.HasOne("EcoTrace.CargoTracking.Domain.Carga", "Carga")
                        .WithMany("Seguimientos")
                        .HasForeignKey("CargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carga");
                });

            modelBuilder.Entity("EcoTrace.CargoTracking.Domain.Carga", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Seguimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
