// <auto-generated />
using System;
using EcoTrace.FleetManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTrace.FleetManagement.Infrastructure.Migrations
{
    [DbContext(typeof(FleetManagementDbContext))]
    partial class FleetManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("EcoTrace.FleetManagement.Domain.Conductor", b =>
                {
                    b.Property<Guid>("ConductorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistradoPorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConductorId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Licencia")
                        .IsUnique();

                    b.ToTable("Conductores", (string)null);
                });

            modelBuilder.Entity("EcoTrace.FleetManagement.Domain.Vehiculo", b =>
                {
                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacidadKg")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistradoPorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("VehiculoId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Vehiculos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
